name: flutter_base_project
description: "A clean and well-structured Flutter base project template with BLoC architecture"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  # Core Flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.0

  # Network & API
  dio: ^5.8.0+1
  connectivity_plus: ^7.0.0
  http: ^1.3.0

  # Local Storage
  shared_preferences: ^2.5.3

  # UI & Utilities
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  dropdown_button2: ^2.3.9
  fluttertoast: ^8.2.4
  loading_overlay: ^0.3.0
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.1

  # Media & Files
  image_picker: ^1.0.4
  flutter_image_compress: ^2.1.0
  mime: ^1.0.4
  path_provider: ^2.1.1

  # Device Info
  device_info_plus: ^12.2.0
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
  #       - asset: assets/fonts/YourFont-Bold.ttf
  #         weight: 700
